network:
  version: 2

  ethernets:
    enp0s3:
      dhcp4: false

      addresses:
        - 7.7.7.2/30

      routes:
        - to: default
          via: 7.7.7.1

      nameservers:
        addresses:
          - 8.8.8.8
          - 1.1.1.1
